### ISSUE TITLE
[Feature Request] Animebytes Integration

### ISSUE THREAD

**Issue by mizz141** [TurboCheetah/sneedex-indexer#10]
Since most releases are on AB, and Prowlarr works better with AB (since it parses multiple names out of a release) it would make sense to have integration for it.

**Comment by TurboCheetah** [comment]
I would love to be able to add AB support, however I am not a member. Not to beg but if you or anyone you know could spare an invite then I could add it 😉 Below are the stats from one of my seedboxes that has been running for ~1 year
![Stats from ~1 year of this seedbox](https://i.turbo.ooo/⁠‌‍‌​​/direct) ![Total torrents](https://i.turbo.ooo/​​⁠​​​/direct)

**Comment by mizz141** [comment]
I sadly can't give you an invite, but I'm more willing to help out with all you need to add support, as a start maybe it would be worth looking into how Prowlarr or Jackett implements it.

**Comment by mizz141** [comment]
Works in v1.1
